name: ci

on:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches:
    - main
    - develop

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: eu-digital-green-certificates/dgca-app-core-ios
        ref: main
        path: dgca-app-core-ios
    - uses: actions/checkout@v2
      with:
        ref: feat/ci
        path: it-dgc-verificaC19-ios
    - name: debug
      run: |-
        ls -la .
    - name: xcode version
      run: |-
        ls /Applications | grep Xcode
        sudo xcode-select -switch /Applications/Xcode_12.4.app
        /usr/bin/xcodebuild -version
    - name: xcode test
      run: |-
        cd ./it-dgc-verificaC19-ios
        xcodebuild test \
        -scheme Verifier \
        -project Verifier.xcodeproj \
        -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' | xcpretty && exit ${PIPESTATUS[0]}
